# baseurl = "http://ocul.on.ca/topomaps/"
baseurl = "https://staticdev.scholarsportal.info/hist-topos/"
title = "Historical Topographic Map Digitization Project - Preserving Ontario’s Past"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-9010354-11"
canonifyURLs = false

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "This website is about the Ontario Council of University Libraries historical topographic maps digitization project"
  sidebarAbout = [
    "<strong>More coming soon!</strong><br><br>The OCUL Historical Topographic Map Digitization project was initiated by the Ontario Council of University Libraries (OCUL) Geo Community in 2014. It is a 2.5 year initiative to digitize and georeference early-to-mid 20th century historical topographic maps covering the province of Ontario at the scales of 1:25,000 and 1:63,360. Our goal is to create and provide access through Scholars Geoportal to a high quality, consistent digital collection that preserves historical topographic information and meets the needs of current and future users. <br><br> The maps on the home page represent a sampling of the approximately 1100 maps in the collection."
  ]
  logo = "img/ocul.png"

# Add to description: Please select Full Collection below to view more.

  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "kaitlin@scholarsportal.info"

# Nav links in the side bar
[[params.navlinks]]
name = "Home"
url = ""

[[params.navlinks]]
name = "About the Maps"
url = "about-maps/"

[[params.navlinks]]
name = "About the Project"
url = "about-project/"

[[params.navlinks]]
name = "Collection Highlights"
url = "highlights/"

[[params.navlinks]]
name = "Using the Maps"
url = "using-maps/"

[[params.navlinks]]
name = "Full Collection"
url = "index/"

[[params.navlinks]]
name = "Contact"
url = "contact/"
