#baseurl = "http://ocul.on.ca/topomaps/"
baseurl = "https://staticdev.scholarsportal.info/topomaps/"
#baseurl = "http://localhost/hist-topos/public/"
theme = "hugo-creative-portfolio-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "topomaps"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-9010354-11"
canonifyURLs = false
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
logo = "img/ocul.png"
style = "blue"
email = "kaitlin@scholarsportal.info"

[params.social]
github = "https://github.com/scholarsportal/historical-topos"
email = "topomaps@scholarsportal.info"

[Languages]
[Languages.en]
languageName = "English"
title = "Historical Topographic Map Digitization Project"
languageCode = "en"
weight = 1
[[Languages.en.navlinks]]
name = "Home"
url = ""
[[Languages.en.navlinks]]
name = "About the Maps"
url = "about-maps/"
[[Languages.en.navlinks]]
name = "About the Project"
url = "about-project/"
[[Languages.en.navlinks]]
name = "Collection Highlights"
url = "highlights/"
[[Languages.en.navlinks]]
name = "Using the Maps"
url = "using-maps/"
[[Languages.en.navlinks]]
name = "Full Collection"
url = "collection/"
[[Languages.en.navlinks]]
name = "Contact"
url = "contact/"

[Languages.fr]
languageName = "Français"
title = "Historical Topographic Map Digitization Project (fr)"
languageCode = "fr"
weight = 2
[[Languages.fr.navlinks]]
name = "Accueil"
url = "fr/"
[[Languages.fr.navlinks]]
name = "About the Maps fr"
url = "fr/about-maps/"
[[Languages.fr.navlinks]]
name = "About the Project fr"
url = "fr/about-project/"
[[Languages.fr.navlinks]]
name = "Collection Highlights fr"
url = "fr/highlights/"
[[Languages.fr.navlinks]]
name = "Using the Maps fr"
url = "fr/using-maps/"
[[Languages.fr.navlinks]]
name = "Full Collection fr"
url = "fr/collection/"
[[Languages.fr.navlinks]]
name = "Contact fr"
url = "fr/contact/"